### ISSUE TITLE
Fabric?

### ISSUE THREAD

**Issue by UltraBlackLinux** [ArtFect/Proxy-Server#2]
I find this mod amazing, but I am using viaFabric, because it's so convenient - please port this to fabric! ;)
I want to test some stuff about an IP banning system I am trying to make.
Thanks alot!

**Comment by DarkReaper231** [comment]
I would also like Fabric port of this

**Comment by ArtFect** [comment]
Updated to Fabric 1.16.5
https://www.curseforge.com/minecraft/mc-mods/proxy-server/files/3184753
